magfest/mivs

- development-defaults.ini
- mivs/configspec.ini
- mivs/templates/emails/game_video_submitted.txt
- mivs/templates/emails/studio_registered.txt
- mivs/templates/mivs_judging/index.html
I implemented the email text changes that Tronster suggested.  I also added Studio links to the admin placeholder page.
> Email text changes

- mivs/automated_emails.py
- mivs/config.py
- mivs/configspec.ini
- mivs/model_checks.py
- mivs/models.py
- mivs/site_sections/mivs_admin.py
- mivs/site_sections/mivs_judging.py
- mivs/templates/emails/videoless_studio.txt
- mivs/templates/mivs_admin/assign_games.html
- mivs/templates/mivs_admin/assign_judges.html
- mivs/templates/mivs_admin/create_judge.html
- mivs/templates/mivs_admin/edit_judge.html
- mivs/templates/mivs_admin/index.html
- mivs/templates/mivs_applications/index.html
- mivs/templates/mivs_base.html
- mivs/templates/mivs_judging/index.html
- mivs/templates/mivs_judging/video_review.html
This is an initial stab at
- creating judges
- assigning judges to games
- allowing judges to post reviews of the videos and screenshots of said games
I'm sending an email to MIVS to make sure that this is roughly in line with their thinking.
One thing which is NOT implemented is automated emails to judges.  That will be simple to add, though I'll want to confer with the MIVS folks about verbiage, etc.
> Judge and review management

- mivs/automated_emails.py
- mivs/templates/emails/final_judging_reminder.txt
- mivs/templates/emails/judge_staffers.txt
I added the requested final email reminder for MIVS judges as well as an email explaining our policy on MIVS judges and staffing.
> added remaining judge-related emails

- mivs/site_sections/mivs_admin.py
- mivs/templates/mivs_admin/index.html
> added screenshots to CSV export and added confirm status to admin page

- mivs/automated_emails.py
- mivs/templates/emails/judge_badge_info.txt
I also made the email queries more efficient, in line with how we're doing better query loading strategies after the performance refactor.
> implemented automated email asked for by MIVS

- mivs/site_sections/mivs_admin.py
MIVS runners need a list of people who should get MIVS ribbons, so that when someone comes to their desk to get a ribbon they can compare their name to the list.
> added csv export for presenters

- development-defaults.ini
merge after https://github.com/magfest/ubersystem-puppet/pull/112
> puppetize allow_game_submission config option

- mivs/configspec.ini
- really need to puppetize this but it'll work here for now
> edit video response expected date

- mivs/model_checks.py
- mivs/templates/mivs_applications/index.html
see #44  for a more detail description of why this is needed
fixes #44
> Url fetch timeout

- mivs/site_sections/mivs_admin.py
> add social media export

- mivs/configspec.ini
> change to correct deadline

- mivs/templates/mivs_applications/confirm.html
> add greater description informing studio that badges can be edited at a later date

- mivs/configspec.ini
- mivs/model_checks.py
- these checks are potentially causing problems for some MIVS studios for seemingly no reason, so disable them
fixes #51 ? maybe? i hope
> add config option, disable by default, to do URL validation checks

- mivs/configspec.ini
- mivs/model_checks.py
fixed per code review, because I HAVE TIME TO WORK ON THIS FOR SOME REASON. crazy.
> fip polarity of config option

- mivs/configspec.ini
Reverts magfest/mivs#58
Turns out we already puppetized this so don't need it, so we'll set it to True in https://github.com/magfest/production-config/pull/133
> Revert "Update configspec.ini"

- mivs/model_checks.py
needed to flip the polarity here, this was a copy+paste typo.
> fix wrong admin check

- mivs/templates/emails/game_submitted.txt
Dates changed to be 2017 relevant
> 2017 update Game Submitted

- mivs/automated_emails.py
- mivs/templates/emails/judge_2016.txt
This is the email the MIVS staff has asked for.
> added new email as requested by the MIVS staff

- mivs/model_checks.py
Surprising no-one, my inability to test this on my local system meant that it didn't work. Hopefully this new change is all that's needed.
> Allow MIVS admins to actually save edits to games

- mivs/config.py
Requested by the MIVS team, since they're on a tighter schedule this year.
> Reduce time diff between soft and hard deadlines

- mivs/models.py
- mivs/templates/mivs_judging/game_review.html
Requested by MIVS as an emergency change.
> Update score to use a 10-point scale

- mivs/templates/emails/game_accepted.txt
> 2017 Game Accepted

- mivs/automated_emails.py
part of email refactoring, merge with https://github.com/magfest/ubersystem/pull/1896
> approval workflow improvements

- mivs/site_sections/mivs_admin.py
MIVS crew are constructing emails by hand for stuff, this will help em out
> add URL of studio edit page to CSV export

- mivs/automated_emails.py
- mivs/models.py
- mivs/site_sections/mivs_admin.py
- mivs/templates/mivs_admin/index.html
- this is to make the client code easier to read
- confirmed means both: game ACCEPTED by our staff, and the studio CONFIRMED they will be present
> add a 'confirmed' property to IndieGame

- mivs/site_sections/mivs_admin.py
- mivs/templates/mivs_admin/assign_games.html
- mivs/templates/mivs_admin/assign_judges.html
- mivs/templates/mivs_judging/index.html
added checkboxes to remove judges from game reviews
> Unnasign judges

- mivs/models.py
- mivs/site_sections/mivs_applications.py
- mivs/templates/mivs_applications/developer.html
- mivs/templates/mivs_applications/index.html
Fixes #31 
Checkbox on Edit Devs page allows devs to set themselves as primary contact (which just means receives emails, there can be multiple).  Devs cannot remove themselves as primary contact if they're the only one left.
> Added button checkbox to receive emails

- mivs/site_sections/mivs_judging.py
fixes #72 
Prevents users from submitting review for a broken/unplayable game with a score.
> Check for broken games having scores

- mivs/automated_emails.py
This pull request directly depends on [#2386](https://github.com/magfest/ubersystem/pull/2386).
> Fixes #2383: Adds static ident arg to each AutomatedEmail instance

- mivs/config.py
- mivs/site_sections/mivs_applications.py
- mivs/templates/mivs_applications/index.html
per @EliAndrewC code suggestion
> turn round1 check into a config mixin to simplify code

- mivs/configspec.ini
- mivs/models.py
Fixes https://github.com/magfest/mivs/issues/72. Also fixes https://github.com/magfest/mivs/issues/71.
> Remove score if the game or video cannot be played

- mivs/site_sections/mivs_admin.py
Fixes https://github.com/magfest/mivs/issues/76
> Use attendee badges for MIVS judges instead of staff

- .gitignore
- mivs/model_checks.py
- mivs/templates/mivs_admin/create_judge.html
- mivs/templates/mivs_admin/edit_judge.html
- mivs/templates/mivs_applications/code.html
- mivs/templates/mivs_applications/developer.html
- mivs/templates/mivs_applications/game.html
- mivs/templates/mivs_applications/index.html
- mivs/templates/mivs_applications/screenshot.html
- mivs/templates/mivs_applications/studio.html
- mivs/templates/mivs_base.html
- mivs/templates/mivs_judging/game_review.html
- mivs/templates/mivs_judging/studio.html
- mivs/templates/mivs_judging/video_review.html
This fix does a few things. Because most of the requested fields
already existed, I didn't actually add any new fields. I made a
few of the fields required. And I made the index page require
at least two screenshots before the video could be submitted.
> Fixes #89: Improves round 1 data collection.

- alembic/versions/5c14f5a350dd_add_platforms_to_judges_and_games.py
- mivs/configspec.ini
- mivs/model_checks.py
- mivs/models.py
- mivs/site_sections/mivs_admin.py
- mivs/site_sections/mivs_applications.py
- mivs/templates/mivs_admin/assign_games.html
- mivs/templates/mivs_admin/assign_judges.html
- mivs/templates/mivs_admin/create_judge.html
- mivs/templates/mivs_admin/edit_judge.html
- mivs/templates/mivs_applications/game.html
- mivs/templates/mivs_applications/index.html
- mivs/templates/mivs_applications/studio.html
Fixes https://github.com/magfest/mivs/issues/17. There were a few things I had to guess on in terms of UI -- for example, I changed the assign pages to prioritize matching judges and games by platform and made it also show if the genres matched -- but hopefully it all makes sense.
> Add platforms to match judges with games

- alembic/versions/938e21c8c260_add_inappropriate_content_column.py
- mivs/models.py
- mivs/site_sections/mivs_judging.py
- mivs/templates/mivs_admin/game_results.html
- mivs/templates/mivs_judging/game_review.html
Fixes https://github.com/magfest/mivs/issues/81.
> Add 'inappropriate content' checkbox for reviews

- alembic/versions/fdaa0d889a48_add_alumni_columns.py
- mivs/config.py
- mivs/configspec.ini
- mivs/models.py
- mivs/templates/mivs_applications/game.html
Fixes https://github.com/magfest/mivs/issues/54.
> Add MIVS Alumni options and update field

- mivs/__init__.py
- mivs/config.py
- mivs/configspec.ini
- mivs/model_checks.py
- mivs/site_sections/mivs_applications.py
- mivs/templates/mivs_applications/index.html
- mivs/templates/mivs_applications/studio.html
Fixes https://github.com/magfest/mivs/issues/99.
> Add a deadline grace period

- mivs/site_sections/mivs_judging.py
- mivs/templates/emails/admin_game_broken.txt
- mivs/templates/emails/admin_video_broken.txt
Fixes https://github.com/magfest/mivs/issues/22.
> Email admins when judges mark videos or games as broken

- mivs/configspec.ini
- mivs/models.py
- mivs/site_sections/mivs_admin.py
- mivs/site_sections/mivs_judging.py
- mivs/templates/emails/admin_game_broken.txt
- mivs/templates/emails/admin_video_broken.txt
- mivs/templates/emails/game_fixed.txt
- mivs/templates/emails/video_fixed.txt
Fixes https://github.com/magfest/mivs/issues/23 and adds some minor code cleanup for the previous PR.
> Email judges when their reviews are reset to Pending

- alembic/versions/a186029770bb_add_waitlisted_date_to_indie_games.py
- mivs/automated_emails.py
- mivs/models.py
- mivs/templates/emails/game_accepted_from_waitlist.txt
Fixes https://github.com/magfest/mivs/issues/28, except that the email probably needs changing.
> Add special "accepted from waitlist" email for game studios

- mivs/templates/emails/judge_intro.txt
Changed start phrasing, Round 2 deadline no longer applicable
> Judging_Intro_2017

- mivs/templates/emails/judge_2016.txt
Updated for this year, added more instructions
> judging_begin_2017

- .gitignore
- alembic/versions/e4d09d36083d_add_third_step_fields_to_mivs_games.py
- mivs/configspec.ini
- mivs/model_checks.py
- mivs/models.py
- mivs/site_sections/mivs_applications.py
- mivs/templates/mivs_applications/index.html
- mivs/templates/mivs_applications/screenshot.html
- mivs/templates/mivs_applications/show_info.html
Fixes https://github.com/magfest/mivs/issues/92.
> Add a post-confirmation step with extra fields for studios

- mivs/models.py
- mivs/templates/mivs_applications/index.html
Fixes https://github.com/magfest/ubersystem/issues/2067.
> Add the Edit link to more places on the studio application page

- mivs/site_sections/mivs_admin.py
- mivs/templates/mivs_admin/judges_owed_refunds.html
Fixes https://github.com/magfest/mivs/issues/75.
> Create 'judges owed refunds' report

- mivs/templates/emails/game_accepted.txt
> 2018 game accepted

- mivs/templates/emails/game_accepted_from_waitlist.txt
> updated for this year

- mivs/models.py
- mivs/site_sections/mivs_admin.py
Both a plain *.xlsx download and a *.zip that includes both the *.xslx and a folder with all the best game screenshot images.
Depends on https://github.com/magfest/ubersystem/pull/3004
> Adds accepted game export

- mivs/automated_emails.py
> adding email to automated_emails.py
